version: "3.8"

services:
  postgres:
    image: postgres:14.5
    container_name: test-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_HOST_AUTH_METHOD: "password"
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 1m
      retries: 10
      start_period: 5s

  backend:
    build:
      context: .
    image: test-backend:0.1
    container_name: test-backend
    ports:
      - "8000:80"
    expose:
      - 8000
    volumes:
      - ./data:/workspace/data
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]

    stdin_open: true
    tty: true
    restart: always



volumes:
  pgdata:
